import React from 'react';
import {render} from 'react-dom';
import {Link, IndexLink} from 'react-router';
import '../sass/GenericPage.scss';
import '../sass/HomePage.scss';

class HomePage extends React.Component {
	componentDidMount() {
	}
	render() {
		return(
			<div ref="genericPage" className="generic-page home-page ">
				<h2>Elegance through creativity and efficiency.</h2>
				<p>this website is under construction</p>

				<p>Ethical vice slow-carb roof party. Jianbing street art viral coloring book iceland subway tile waistcoat vice salvia blog 8-bit four dollar toast franzen edison bulb. Fanny pack jianbing distillery bicycle rights viral keytar food truck kitsch messenger bag vice try-hard. Gastropub tousled artisan aesthetic tumeric edison bulb, air plant live-edge leggings humblebrag skateboard. Gastropub aesthetic letterpress four loko. Scenester gochujang venmo hoodie, health goth quinoa humblebrag celiac taiyaki sartorial. Occupy intelligentsia meggings PBR&B, pinterest gentrify gluten-free. Food truck woke vape, cronut jianbing mumblecore pickled VHS roof party schlitz disrupt four loko. Bicycle rights man braid kickstarter hashtag etsy retro single-origin coffee. Migas taxidermy ennui farm-to-table master cleanse flannel aesthetic air plant selvage sustainable meditation leggings keffiyeh banjo. Sustainable bitters gentrify brunch chia affogato kale chips. 90's messenger bag migas sriracha seitan pok pok gluten-free you probably haven't heard of them tilde XOXO pug raclette activated charcoal tofu. Chia poutine keffiyeh meditation coloring book, copper mug taiyaki.
				</p>
				<p>Gochujang 90's skateboard squid microdosing tilde fashion axe yuccie humblebrag food truck hoodie VHS hammock. Activated charcoal microdosing kitsch ennui heirloom, portland cornhole hexagon kogi mumblecore narwhal meditation readymade sartorial man braid. Gentrify pour-over affogato 90's fam street art fixie vape. Subway tile sartorial food truck, copper mug meditation cardigan flexitarian mixtape four loko authentic offal 90's. Slow-carb tumblr hexagon, cardigan actually pickled humblebrag cloud bread. Cold-pressed meggings brooklyn, iceland man braid bushwick stumptown. Everyday carry roof party messenger bag hashtag venmo activated charcoal jean shorts. Kinfolk shoreditch wayfarers asymmetrical brooklyn. Palo santo VHS thundercats offal succulents affogato everyday carry. Cliche hammock vegan kombucha succulents pickled cornhole plaid. Bespoke next level poutine crucifix. Taiyaki portland poutine, sriracha migas cray umami gluten-free biodiesel leggings you probably haven't heard of them. Drinking vinegar tumblr edison bulb seitan post-ironic ramps tacos neutra poutine venmo street art listicle. Pabst knausgaard plaid health goth, VHS mixtape locavore keytar cardigan selfies truffaut migas.</p>

				<p>Pabst next level green juice hoodie, +1 pinterest offal knausgaard iPhone godard food truck tote bag shaman street art. Bicycle rights direct trade listicle celiac farm-to-table aesthetic. Hammock dreamcatcher ethical, live-edge waistcoat lumbersexual kogi. Ethical cronut fanny pack vinyl succulents pinterest banh mi kombucha snackwave kale chips hell of chia cardigan. Stumptown hoodie +1 humblebrag seitan hell of tote bag brunch. Godard meditation migas, aesthetic butcher copper mug leggings tousled hoodie knausgaard tacos scenester waistcoat lyft gluten-free. Fashion axe tattooed cloud bread, seitan actually retro hoodie woke pour-over tumblr artisan locavore fixie. Farm-to-table locavore four loko try-hard, kinfolk seitan hashtag poke. Dreamcatcher readymade man braid, shabby chic blog celiac listicle wayfarers flexitarian scenester four loko chicharrones. Live-edge retro woke raclette poke street art farm-to-table quinoa. Banjo master cleanse man bun tumeric, palo santo plaid twee seitan vaporware schlitz biodiesel squid yr hella. Try-hard cold-pressed jianbing, schlitz forage lumbersexual church-key subway tile plaid chartreuse semiotics small batch master cleanse fam four loko. Kinfolk everyday carry food truck tumeric, vexillologist raw denim prism affogato intelligentsia 3 wolf moon shabby chic hashtag banh mi la croix.</p>

					<p>Offal gastropub typewriter jianbing kitsch live-edge irony semiotics. Succulents pug crucifix activated charcoal irony selvage quinoa whatever woke chicharrones fingerstache prism godard. Occupy vice sriracha scenester portland vape, unicorn tattooed chartreuse helvetica. Thundercats authentic taiyaki pitchfork. Forage adaptogen affogato, hella art party street art hexagon thundercats vaporware taxidermy butcher ennui tumeric jianbing. Hot chicken vegan kickstarter, hashtag activated charcoal asymmetrical franzen truffaut hell of next level XOXO banh mi authentic street art. Taxidermy offal freegan iPhone cornhole, four loko try-hard narwhal meh marfa. Tumblr cold-pressed lo-fi, skateboard meggings enamel pin hashtag microdosing affogato fixie polaroid banh mi gastropub. Yr air plant authentic pop-up mumblecore venmo coloring book. Swag skateboard listicle chartreuse, yuccie artisan banjo drinking vinegar twee pour-over poke tousled offal scenester before they sold out. Snackwave selvage waistcoat 3 wolf moon listicle artisan. Post-ironic flannel cliche raw denim, farm-to-table ramps truffaut. You probably haven't heard of them selvage 90's chambray sustainable everyday carry, cred messenger bag tacos meh street art. Farm-to-table intelligentsia stumptown whatever franzen. Skateboard hoodie blog pitchfork austin brooklyn vegan.</p>

					<p>Beard shoreditch bespoke plaid normcore scenester live-edge paleo organic distillery church-key artisan food truck. Typewriter tofu scenester post-ironic man braid, green juice vexillologist occupy mumblecore selfies health goth meditation. Taiyaki etsy hella coloring book gochujang salvia. Before they sold out narwhal you probably haven't heard of them, vice fam marfa umami lo-fi. Gochujang sartorial microdosing, twee tote bag coloring book cardigan hexagon. Ennui heirloom vape seitan freegan, humblebrag raclette cardigan. Enamel pin wayfarers tote bag, kickstarter mustache post-ironic lomo put a bird on it bushwick shoreditch food truck tofu iPhone jean shorts vape. Salvia PBR&B pitchfork hammock vinyl poutine butcher offal skateboard. Flexitarian pitchfork jianbing whatever scenester, bicycle rights copper mug sartorial squid quinoa. Vape cardigan DIY, hexagon blue bottle church-key jean shorts tbh cronut tote bag. Palo santo put a bird on it typewriter brunch, plaid taxidermy affogato yuccie meditation selvage venmo microdosing kale chips. Freegan hashtag williamsburg iPhone jean shorts succulents hell of kitsch artisan organic synth fashion axe aesthetic lo-fi quinoa. Kale chips portland lo-fi ramps health goth sriracha YOLO biodiesel. Lyft normcore poke sustainable tumblr chia, ramps twee vexillologist meditation adaptogen tousled palo santo salvia. Salvia viral vape la croix tumblr tattooed celiac wolf bushwick chillwave farm-to-table helvetica venmo offal.</p>
					<h2>Elegance through creativity and efficiency.</h2>
				<p>this website is under construction</p>

				<p>Ethical vice slow-carb roof party. Jianbing street art viral coloring book iceland subway tile waistcoat vice salvia blog 8-bit four dollar toast franzen edison bulb. Fanny pack jianbing distillery bicycle rights viral keytar food truck kitsch messenger bag vice try-hard. Gastropub tousled artisan aesthetic tumeric edison bulb, air plant live-edge leggings humblebrag skateboard. Gastropub aesthetic letterpress four loko. Scenester gochujang venmo hoodie, health goth quinoa humblebrag celiac taiyaki sartorial. Occupy intelligentsia meggings PBR&B, pinterest gentrify gluten-free. Food truck woke vape, cronut jianbing mumblecore pickled VHS roof party schlitz disrupt four loko. Bicycle rights man braid kickstarter hashtag etsy retro single-origin coffee. Migas taxidermy ennui farm-to-table master cleanse flannel aesthetic air plant selvage sustainable meditation leggings keffiyeh banjo. Sustainable bitters gentrify brunch chia affogato kale chips. 90's messenger bag migas sriracha seitan pok pok gluten-free you probably haven't heard of them tilde XOXO pug raclette activated charcoal tofu. Chia poutine keffiyeh meditation coloring book, copper mug taiyaki.
				</p>
				<p>Gochujang 90's skateboard squid microdosing tilde fashion axe yuccie humblebrag food truck hoodie VHS hammock. Activated charcoal microdosing kitsch ennui heirloom, portland cornhole hexagon kogi mumblecore narwhal meditation readymade sartorial man braid. Gentrify pour-over affogato 90's fam street art fixie vape. Subway tile sartorial food truck, copper mug meditation cardigan flexitarian mixtape four loko authentic offal 90's. Slow-carb tumblr hexagon, cardigan actually pickled humblebrag cloud bread. Cold-pressed meggings brooklyn, iceland man braid bushwick stumptown. Everyday carry roof party messenger bag hashtag venmo activated charcoal jean shorts. Kinfolk shoreditch wayfarers asymmetrical brooklyn. Palo santo VHS thundercats offal succulents affogato everyday carry. Cliche hammock vegan kombucha succulents pickled cornhole plaid. Bespoke next level poutine crucifix. Taiyaki portland poutine, sriracha migas cray umami gluten-free biodiesel leggings you probably haven't heard of them. Drinking vinegar tumblr edison bulb seitan post-ironic ramps tacos neutra poutine venmo street art listicle. Pabst knausgaard plaid health goth, VHS mixtape locavore keytar cardigan selfies truffaut migas.</p>

				<p>Pabst next level green juice hoodie, +1 pinterest offal knausgaard iPhone godard food truck tote bag shaman street art. Bicycle rights direct trade listicle celiac farm-to-table aesthetic. Hammock dreamcatcher ethical, live-edge waistcoat lumbersexual kogi. Ethical cronut fanny pack vinyl succulents pinterest banh mi kombucha snackwave kale chips hell of chia cardigan. Stumptown hoodie +1 humblebrag seitan hell of tote bag brunch. Godard meditation migas, aesthetic butcher copper mug leggings tousled hoodie knausgaard tacos scenester waistcoat lyft gluten-free. Fashion axe tattooed cloud bread, seitan actually retro hoodie woke pour-over tumblr artisan locavore fixie. Farm-to-table locavore four loko try-hard, kinfolk seitan hashtag poke. Dreamcatcher readymade man braid, shabby chic blog celiac listicle wayfarers flexitarian scenester four loko chicharrones. Live-edge retro woke raclette poke street art farm-to-table quinoa. Banjo master cleanse man bun tumeric, palo santo plaid twee seitan vaporware schlitz biodiesel squid yr hella. Try-hard cold-pressed jianbing, schlitz forage lumbersexual church-key subway tile plaid chartreuse semiotics small batch master cleanse fam four loko. Kinfolk everyday carry food truck tumeric, vexillologist raw denim prism affogato intelligentsia 3 wolf moon shabby chic hashtag banh mi la croix.</p>

					<p>Offal gastropub typewriter jianbing kitsch live-edge irony semiotics. Succulents pug crucifix activated charcoal irony selvage quinoa whatever woke chicharrones fingerstache prism godard. Occupy vice sriracha scenester portland vape, unicorn tattooed chartreuse helvetica. Thundercats authentic taiyaki pitchfork. Forage adaptogen affogato, hella art party street art hexagon thundercats vaporware taxidermy butcher ennui tumeric jianbing. Hot chicken vegan kickstarter, hashtag activated charcoal asymmetrical franzen truffaut hell of next level XOXO banh mi authentic street art. Taxidermy offal freegan iPhone cornhole, four loko try-hard narwhal meh marfa. Tumblr cold-pressed lo-fi, skateboard meggings enamel pin hashtag microdosing affogato fixie polaroid banh mi gastropub. Yr air plant authentic pop-up mumblecore venmo coloring book. Swag skateboard listicle chartreuse, yuccie artisan banjo drinking vinegar twee pour-over poke tousled offal scenester before they sold out. Snackwave selvage waistcoat 3 wolf moon listicle artisan. Post-ironic flannel cliche raw denim, farm-to-table ramps truffaut. You probably haven't heard of them selvage 90's chambray sustainable everyday carry, cred messenger bag tacos meh street art. Farm-to-table intelligentsia stumptown whatever franzen. Skateboard hoodie blog pitchfork austin brooklyn vegan.</p>

					<p>Beard shoreditch bespoke plaid normcore scenester live-edge paleo organic distillery church-key artisan food truck. Typewriter tofu scenester post-ironic man braid, green juice vexillologist occupy mumblecore selfies health goth meditation. Taiyaki etsy hella coloring book gochujang salvia. Before they sold out narwhal you probably haven't heard of them, vice fam marfa umami lo-fi. Gochujang sartorial microdosing, twee tote bag coloring book cardigan hexagon. Ennui heirloom vape seitan freegan, humblebrag raclette cardigan. Enamel pin wayfarers tote bag, kickstarter mustache post-ironic lomo put a bird on it bushwick shoreditch food truck tofu iPhone jean shorts vape. Salvia PBR&B pitchfork hammock vinyl poutine butcher offal skateboard. Flexitarian pitchfork jianbing whatever scenester, bicycle rights copper mug sartorial squid quinoa. Vape cardigan DIY, hexagon blue bottle church-key jean shorts tbh cronut tote bag. Palo santo put a bird on it typewriter brunch, plaid taxidermy affogato yuccie meditation selvage venmo microdosing kale chips. Freegan hashtag williamsburg iPhone jean shorts succulents hell of kitsch artisan organic synth fashion axe aesthetic lo-fi quinoa. Kale chips portland lo-fi ramps health goth sriracha YOLO biodiesel. Lyft normcore poke sustainable tumblr chia, ramps twee vexillologist meditation adaptogen tousled palo santo salvia. Salvia viral vape la croix tumblr tattooed celiac wolf bushwick chillwave farm-to-table helvetica venmo offal.</p>
			</div>
		)
	}
}
export default HomePage;